version: '2'
services:
  etcd:
    image: "quay.io/coreos/etcd:v3.3"
    command: "etcd --advertise-client-urls http://0.0.0.0:2379 --listen-client-urls http://0.0.0.0:2379"
    ports:
      - 2379:2379

  k8s-api:
    image: "gcr.io/google-containers/hyperkube-amd64:v1.14.1"
    depends_on:
      - "etcd"
    command: "/hyperkube apiserver --insecure-bind-address=0.0.0.0 --etcd-servers=http://etcd:2379 --service-cluster-ip-range=10.0.0.0/16 --admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ResourceQuota"
    ports:
      - 8080:8080

  k8s-scheduler:
    image: "gcr.io/google-containers/hyperkube-amd64:v1.14.1"
    depends_on:
      - "k8s-api"
    command: "/hyperkube scheduler --master=k8s-api:8080"

  k8s-controller-manager:
    image: "gcr.io/google-containers/hyperkube-amd64:v1.14.1"
    depends_on:
      - "k8s-api"
    command: "/hyperkube kube-controller-manager --master=k8s-api:8080"

  nodus:
    image: "nodus:latest"
    depends_on:
      - "k8s-api"
    command: "sleep 24h"
