apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  selector:
    matchLabels:
      app: test-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: test-deployment
        np.class: deployment-test
        np.runDuration: 5s
        np.terminalPhase: Succeeded
    spec:
      # Need this as the controller manager marks a node unreachable
      tolerations:
      - key: node.kubernetes.io/unreachable
        effect: NoSchedule
      containers:
      - name: test-deployment
        image: ubuntu:16.04
